provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  gh-push:
    lang: go
    handler: ./gh-push
    image: alexellis2/gh-push:0.3.3
    environment:
      # Http_X_Github_Event: push
      read_timeout: 10
      write_timeout: 10
      write_debug: true
      read_debug: true
      validate_customers: true
      customers_url: "https://raw.githubusercontent.com/openfaas/openfaas-cloud/master/CUSTOMERS"
    environment_file:
      - gateway_config.yml
      - github.yml

  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: alexellis2/of-git-tar:0.6.4
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: alexellis2/of-buildshiprun:0.4.5
    environment:
      read_timeout: 300
      write_timeout: 300
      write_debug: true
      read_debug: true
      builder_url: http://of-builder.openfaas:8080/
    environment_file:
      - buildshiprun_limits_swarm.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - basic-auth-user
      - basic-auth-password

  list-functions:
    lang: go
    handler: ./list-functions
    image: alexellis2/list-functions:0.4.2
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: alexellis2/garbage-collect:0.3.1
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30
      write_timeout: 30
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  git-event:
    lang: go
    handler: ./git-event
    image: alexellis2/git-event:0.3.1
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml
      - gateway_config.yml

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: alexellis2/import-secrets:0.0.1

  echo:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    environment:
      write_debug: true
      read_debug: true

  audit-event:
    lang: go
    handler: ./audit-event
    image: functions/audit-event:0.1.0
    environment_file:
      - slack.yml

