apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-router
  labels:
    app.kubernetes.io/name: openfaas-cloud
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: edge-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-router
  template:
    metadata:
      annotations:
        prometheus.io.scrape: {{ .Values.global.prometheusScrape | quote }}
      labels:
        app: edge-router
    spec:
      containers:
        - name: edge-router
          image: {{ .Values.edgeRouter.container }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          readinessProbe:
            {{- if .Values.global.httpProbe }}
            httpGet:
              path: /healthz
              port: 8080
            {{- else }}
            exec:
              command:
                - wget
                - --quiet
                - --tries=1
                - --timeout=5
                - --spider
                - http://localhost:8080/healthz
            {{- end }}
            timeoutSeconds: 5
          env:
            - name: upstream_url
              value: "http://gateway.{{ .Values.global.openfaasNamespace }}:8080"
            - name: port
              value: "8080"
            - name: timeout
              value: "60s"
            # For OAuth 2.0
            - name: auth_url
            {{- if .Values.global.enableOAuth2 }}
              value: "http://edge-auth.{{ .Values.global.openfaasNamespace }}:8080"
            {{- else }}
              value: "http://echo.{{ .Values.global.openfaasFunctionsNamespace }}:8080"
            {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
