apiVersion: v1
kind: ServiceAccount
metadata:
  name: of-builder
  namespace: openfaas
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: of-builder
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - secret
  - configMap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: of-builder
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - of-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: of-builder-psp
  namespace: openfaas
roleRef:
  kind: Role
  name: of-builder
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: of-builder
  namespace: openfaas