apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openfaas-auth-ingress
  namespace: {{ .Values.global.coreNamespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingressClass | quote }}
    nginx.ingress.kubernetes.io/limit-connections: "20"
    nginx.ingress.kubernetes.io/limit-rpm: "600"
  labels:
    app: faas-netesd
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    - {{ printf "auth.system.%s" .Values.global.rootDomain | quote }}
    secretName: auth-system-{{ .Values.global.rootDomain }}-cert
  {{- end }}
  rules:
  - host: {{ printf "auth.system.%s" .Values.global.rootDomain | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: edge-router
          servicePort: 8080
