apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: of-builder
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: of-builder
    spec:
      containers:
      - name: of-builder
        image: openfaas/of-builder:0.3.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true
