apiVersion: v1
kind: Service
metadata:
  name: of-buildkit
  namespace: openfaas
  labels:
    app: of-buildkit
spec:
  type: ClusterIP
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: of-buildkit
